### ISSUE TITLE
Qt6 Error

### ISSUE THREAD

**Issue by BEST8OY** [hgiesel/closet#102]
Closet does not run on Qt6 Anki variant.

![Screenshot 2022-08-09 111934](https://user-images.githubusercontent.com/70865987/183583232-30e0b863-acbe-4bac-9352-28e715568af9.jpg)

**Comment by hgiesel** [comment]
qt5 and qt6 files were not included in the build script. I will update it properly this evening.

**Comment by BEST8OY** [comment]
>I will update it properly this evening.
Just reminding.
@hgiesel

**Comment by BEST8OY** [comment]
Fixed.
