### ISSUE TITLE
2.1.54 qt 5 still not working

### ISSUE THREAD

**Issue by AnKingMed** [hgiesel/closet#103]
**Describe the bug**
Error code on starting Anki. Add-on doesn't work

> ⁨Traceback (most recent call last):
>   File "aqt.addons", line 244, in loadAddons
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/272311064/__init__.py", line 1, in <module>
>     from .src import init
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/272311064/src/__init__.py", line 10, in <module>
>     from .models import init_models_dialog
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/272311064/src/models.py", line 7, in <module>
>     from ..gui.model_settings import ModelSettings
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/272311064/gui/model_settings.py", line 5, in <module>
>     from .forms.qt5.model_settings_ui import Ui_Settings
> ModuleNotFoundError: No module named '272311064.gui.forms.qt5'

- Anki client: [e.g. AnkiDesktop, AnkiDroid, AnkiMobile on iOS, AnkiWeb]
Anki 2.1.54Qt5

**Comment by AnKingMed** [comment]
I've had multiple people report the same error to me

**Comment by kleinerpirat** [comment]
Yeah, that's to be expected - it affects 100% of users (Qt5 and Qt6).

The issue is that the package Henrik uploaded to AnkiWeb didn't include the folders for the different Qt versions. They're created with the build script used for development and testing, but for some reason they weren't shipped in the `.ankiaddon` package.

**Comment by BEST8OY** [comment]
https://github.com/hgiesel/closet/issues/102
Henrik was going to fix it two days ago.
Maybe something happened!
We should wait I suppose.

**Comment by hgiesel** [comment]
I just updated. It hope that solves it :)

**Comment by kleinerpirat** [comment]
I just downloaded your update. Both qt folders are now shipped, but the files `model_settings_ui.py` and `settings_ui.py` are empty in the qt5 folder.

**Comment by hgiesel** [comment]
Ok, I think I figured out. It was basically a problem with my python install and `pyuic5` was failing quietly.
I've updated again, and this time I'm pretty confident it works :)
