### ISSUE TITLE
Hide cmds fields, if they are not required

### ISSUE THREAD

**Issue by hgiesel** [hgiesel/closet#24]
Not sure how this should behave, maybe a toggle?:
1. Display all
1. Display filled
1. Display none

**Comment by abedahmeduhp** [comment]
display none

**Comment by hgiesel** [comment]
I will probably outsource this to a different add-on, once I do this

**Comment by hgiesel** [comment]
Is now the add-on [Collapsible Fields](https://ankiweb.net/shared/info/1896168623)!
