### ISSUE TITLE
Found a bug  on linux (no error shown)

### ISSUE THREAD

**Issue by abedahmeduhp** [hgiesel/closet#25]
i add the following picture inside Anki and using Closet: 
![image](https://user-images.githubusercontent.com/62298107/94375355-f49a8480-010a-11eb-943b-fff55d4b54f2.png)
when i display the card  :
![image](https://user-images.githubusercontent.com/62298107/94375365-0aa84500-010b-11eb-8d88-063c47f74d44.png)

Can you fix it please ?

My system is : Linux Mint 
Anki Version :
![image](https://user-images.githubusercontent.com/62298107/94375417-58bd4880-010b-11eb-8bb8-cb92e34040b5.png)

**Comment by hgiesel** [comment]
I'm afraid it's because a bug that I introduced when updating Closet. You would help me immensely by installing [AnkiWebView Inspector](https://ankiweb.net/shared/info/31746032) and looking at the debug output in the console when that bug occurs.

**Comment by abedahmeduhp** [comment]
i receive no error using Inspector 
![Uploading image.png…]()

**Comment by hgiesel** [comment]
When opening the console can you run `initCloset()`?

**Comment by abedahmeduhp** [comment]
sure
![Uploading image.png…]()

**Comment by abedahmeduhp** [comment]
if you need , i can use teamviewer

**Comment by hgiesel** [comment]
You probably don't have Closet installed.
[https://www.youtube.com/watch?v=9o7uriyIKnw&t=2736s](Watch the installation video).
You only need to watch the first three minutes for the installation.

**Comment by hgiesel** [comment]
No response for almost 30 days, if you still have questions, open a new issue
