### ISSUE TITLE
Numbered clozes don't work

### ISSUE THREAD

**Issue by Acuelatus** [hgiesel/closet#26]
Hi there!,

Numbered clozes don't work for me. I don't know if I´m doing something wrong but they always show revealed.

One example:

[[c1::Test]] The word Text is always on display
[[cr1::Test]] Works great
[[ch1::Test]] Works great

I´m using Anki 2.1.34 on Mac with latest Closet for Anki update.

**Comment by hgiesel** [comment]
When numbered clozes have a number bigger than 1, than they react to the "current card number". That number can be inferred by the name of card type. For more info, [look here](https://closetengine.com/how-to-use#card-numbers).

You can make your example work by using "c0" instead of "c1".

**Comment by Acuelatus** [comment]
Ups!, thanks for your answer!!, all was muy fault.
