### ISSUE TITLE
Make delimiters configurable

### ISSUE THREAD

**Issue by hgiesel** [hgiesel/closet#28]
Specifically `TAG_OPEN`, `TAG_CLOSE`, `ARG_SEP`.

**Comment by hgiesel** [comment]
Supported since 3c105d856a04ac0e407dab8a454b2cce62a4ba88.

In order to set custom delimiters, you must call `closet.setDelimiters('[[', '::', ']]')`, where `[[` is the open delimiter, `::` the initial argument separator, and `]]` the closing delimiter.

**Comment by Incina76** [comment]
how would i go about this? I'm not sure what you mean by call.

**Comment by hgiesel** [comment]
Okay, so I revamped it, and thoroughly tested it this time.

Here's what you're gonna have to do:

1. You go into the "Assets..." menu, select "Closet Setup"

2. At an empty spot in the code, you paste this:
````javascript
const delimiters =  {
    open: '&lt;&lt;',
    sep: '::',
    close: '&gt;&gt;'
}
```
As you can see, this contains the delimiters you want to use, `&lt;&lt;` corresponding to `<<`, etc.

3. At the end of this setup, you change this:
```javascript
return [[
    elements,
    memoryMap,
    filterManager,
]]
```
into:
```javascript
return [[
    elements,
    memoryMap,
    filterManager,
    { delimiters },
]]
```

Now it should work.
Tell me, if it works out for you.

**Comment by Incina76** [comment]
Ok its working with <<>> fine. On my cards i ended up using {{ }} but changing the config to
```
const delimiters =  {
    open: '{{',
    sep: '::',
    close: '}}'
}
```
I get this error in preview.

Front template has a problem:
Found '⁨{{', sep: '::', close: '}}⁩', but there is no field called '⁨ '⁩'
More information

I can switch over my cards to use << >> though

**Comment by hgiesel** [comment]
You can circumvent this error by using backslashes:

```javascript
const delimiters =  {
    open: '\{\{',
    sep: '::',
    close: '\}\}'
}
```

**Comment by Incina76** [comment]
that worked thank you. your awesome.
