### ISSUE TITLE
Wont mix

### ISSUE THREAD

**Issue by DoctorToBeIn23** [hgiesel/closet#32]
It looks like it is mixing in the preview window but not when actually studying...

Link to my 2 card types https://drive.google.com/file/d/1xwVGVapA7ttB_STlOsqzr51ODZeA1MLZ/view?usp=sharing

mac os Catalina 
anki 2.1.33

**Comment by hgiesel** [comment]
I had a look.

You need to use `[[mix1::<picture>]]` instead of `[[mix::<picture>]]`.
All instances of `mix1` will randomly shuffled.

**Comment by DoctorToBeIn23** [comment]
Thank you sorry I missed that! I should have noticed that.

**Comment by hgiesel** [comment]
No problem.
