### ISSUE TITLE
Flaschcard features

### ISSUE THREAD

**Issue by Acuelatus** [hgiesel/closet#36]
Hi hgiesel!,

There´s no way to make "flashcard features" work. I spent 2 days trying it and now it´s time for some help. I followed the instructions in youtube video. I have lastes stable Anki 2.35 an latest Closet update.

Here´s an exported deck with one single card if it helps to undestand what is happening or what i´m doing wrong: https://www.dropbox.com/s/mi6zoalf9qt5v5u/Reveal%20On%20Key%20Press%20Test.apkg?dl=0

Thanks for your time!!

**Comment by hgiesel** [comment]
Hi!

there are actual two separate issues at play here:

1. There is an issue with the "reveal on key down" script itself. For this, go into Asset Manager, lookup the script, and fix those two lines:

```js
    const revealOnQ = makeObscureOnKd(KeyEvent.DOM_VK_Q, '6')
    const revealAllOnW = makeObscureOnKdAll(KeyEvent.DOM_VK_W, '5')
```

...to...

```js
    const revealOnQ = makeObscureOnKd(81 /* Q */, '6')
    const revealAllOnW = makeObscureOnKdAll(87 /* W */, '5')
```

2. There is an issue introduced with a new version of Closet. I'm trying to make it behave with the built-in MathJax, and for those I sadly had to make this breaking change:
To fix it, go into the "Closet Setup" in Asset manager, and change:

```js
revealOnKey(filterManager)
```

..into...

```js
revealOnKey(closet, filterManager)
```

Next, go into Reveal clozes on key press, and in the first line, change

```js
function revealOnKey(filterManager) {
```

...into...

```js
function revealOnKey(closet, filterManager) {
```

Now it should work!

**Comment by Acuelatus** [comment]
Now is working!!, thanks for your help and enjoy your coffee, you won it!!
