### ISSUE TITLE
Help me create image occlusion cards

### ISSUE THREAD

**Issue by gaetanKeribin** [hgiesel/closet#37]
**Describe the bug**
 - Anki client: [e.g. **AnkiDesktop**, AnkiDroid, AnkiMobile on iOS, AnkiWeb]
 - if AnkiDesktop, please name your OS [e.g. Windows, macOS, **Linux**]
 - if AnkiDesktop, please name the version. You can find it in the "About" section [e.g. 2.1.26] **2.1.35**

Hi, first of all, thank you for your work! I'm having a hard time getting images occlusions to work though. It seems everything is fine until I try to review them and only the first card is generated from the first occlusion on the image. Btw I read on the add-on page that the add-on only works with anki up to 2.1.32. Is it still the case?

**Debug information**

#### Method 1
**No error in console log to be found.**

#### Method 2
Thanks a lot again.
[CH topic voc.zip](https://github.com/hgiesel/closet/files/5572845/CH.topic.voc.zip)

**Comment by hgiesel** [comment]
When using Closet with more elaborate configurations, it needs a little bit of setup, which can get a little complicated, if you don't have a programming background.
However, I've done it for you. If you open the deck, you will find that it now has 81 cards, and it has a new card type called `ClosetSource`. Please use this note type in the future to make the image occlusions.

You can make up to 25 image occlusions per image, no more, please split up the picture if you have more than that.

On one of the images, I also made examples using clozes and multiple choice questions, in case you're interested in them. I think looking at the field content, should give you enough information to recreate it yourself.

[CH topic voc_new.apkg.zip](https://github.com/hgiesel/closet/files/5573669/CH.topic.voc_new.apkg.zip)

**Comment by gaetanKeribin** [comment]
Thank you very much ! Just tried it, it works great !

**Comment by hgiesel** [comment]
Great. Also thanks a lot for the support! Really appreciate it!
