### ISSUE TITLE
Question/ Feature Request: syntax highlighting

### ISSUE THREAD

**Issue by sandersantema** [hgiesel/closet#52]
I was wondering whether syntax highlighting using something like [highlightjs](https://highlightjs.org/) would be possible. I'm not well versed enough in web technologies and such to estimate whether it would be. But if it is possible in the current closet framework I could investigate and see if I'd be able to get it working.

What I'd like to see is being able to have the following example code (are linebreaks permitted?):
```
[[code::
const frontStylizer = backStylizer.toStylizer({
    mapper: wrapWithBrackets,
})
]]
```
Appear as:
```javascript
const frontStylizer = backStylizer.toStylizer({
    mapper: wrapWithBrackets,
})
```

And to be able to add a cloze with properly highlighted code while the cloze is properly styled too:
```javascript
const frontStylizer = backStylizer.toStylizer({
    mapper: [[c::wrapWithBrackets]],
})
```

Although this might need to be part of a more generalized styling part of closet given that customizations such as being able to set the monotype font to use in `[[code::...]]` should be part of a generalized way to set customs fonts and such.

**Comment by hgiesel** [comment]
In case you just want static syntax highlighting, I would recommend the [Syntax Highlighting](https://ankiweb.net/shared/info/1463041493) add-on. The big strength of Closet is to have add dynamic effects, and differ content being different on the front vs. on the back. If there's nothing dynamic about it, it might be overkill to use Closet for it. Especially language syntax analysis would probably take a moment.
