### ISSUE TITLE
2.1.45 Alpha 1 -> add-on Broken 

### ISSUE THREAD

**Issue by NameLessGO** [hgiesel/closet#63]
**Thanks for the add-on!**
breakages (Probably will be fixed in the next Alpha because "The next alpha will add an alias for NoteType"

AnkiDesktop
Windows 10
2.1.45+ Alpha 1
i put only this info because was when i started Anki 
![image](https://user-images.githubusercontent.com/66227691/118669444-be0d9900-b7c3-11eb-94ef-d713215653ad.png)

**Comment by hgiesel** [comment]
This particular issue was indeed fixed later on.
