### ISSUE TITLE
Allow to pass `DeferredOptions` when using `closet.wrappers.{deferred,aftermath}`

### ISSUE THREAD

**Issue by hgiesel** [hgiesel/closet#72]
https://forums.ankiweb.net/t/closet-for-anki-official-support/4560/139?u=hengiesel

**Comment by rumDMC** [comment]
Following from AnkiWeb. Trying to get Occlusion to allow me to reveal each individual box at a time when I click on it. Hopelessly  lost as to how to make it happen

**Comment by hgiesel** [comment]
Fixed on upstream (0.5.5)
