### ISSUE TITLE
Closet is not working in AnkiDroid on certain devices.

### ISSUE THREAD

**Issue by talenelat-elin** [hgiesel/closet#73]
Preface: I'm unsure of the complete extent or cause of the problem

The problem: The clozes and occlusions are not rendered at all, instead the contents of the fields are shown, including the closet notation, like so: 
![image](https://user-images.githubusercontent.com/71895835/126846447-433e77d0-0ae4-4e81-80fd-5fbe612b8714.png)
In a functioning card, the contents of the double square brackets should have been replaced by `[...]` in the front of the card.

How I test it:
1. Delete all the ankidroid files present from previous installs, if any.
2. Fresh install of ankidroid from the play store
3. Import an apkg file of closet cards that I've created (that definitely work on Anki Windows)- [LINK](https://mega.nz/file/zbAiQbLD#OWMPaRsV00eEJTMCN7RQAOzf9ymrUN6NuDnSiSRBQYQ)
4. Check the cards

So far, I've tested 6 devices:

1. Xiaomi Redmi Note 5 Pro - broken
2. Xiaomi Redmi Note 9 Pro - broken
3. Xiaomi Redmi Note 7 Pro - broken
4. Lenovo K9 - Broken
5. OnePlus 6 - Works
6. RealMe 2 - Works

I'd appreciate it if people could import the deck and check out the cards on their devices and add to the data.

Cards made in: 
    Anki Windows (x64) 2.1.41
    Closet 0.5.3
Tested in:
    AnkiDroid 2.15.6

**Comment by hgiesel** [comment]
Thanks for the report.

Please check the Android versions of those individual devices. The support for loading ES modules (which is what Closet needs) was only added with 2.15.

**Comment by talenelat-elin** [comment]
> 
> 
> Thanks for the report.
> 
> Please check the Android versions of those individual devices. The support for loading ES modules (which is what Closet needs) was only added with 2.15.

@hgiesel It seems that it's not working in Android versions 9 and below.

<table><thead><tr><th>Phone</th><th>status<br></th><th>Android Version</th></tr></thead><tbody><tr><td>Xiaomi Redmi Note 5 Pro</td><td>broken<br></td><td>9 PKQ1.180904.001</td></tr><tr><td>Xiaomi Redmi Y2</td><td>broken</td><td>9 PKQ1.181203.001</td></tr><tr><td>Lenovo K9</td><td>broken</td><td>8.1.0</td></tr><tr><td>Xiaomi Poco M2<br></td><td>working</td><td>10 QP1A.190711.020</td></tr><tr><td>OnePlus 6</td><td>working</td><td>10 (OxygenOS v10.3.11)</td></tr><tr><td>Realme 2 Pro</td><td>working<br></td><td>10 (Realme UI V1.0)<br></td></tr></tbody></table>

**Comment by hgiesel** [comment]
@talenelat-elin Thanks a lot for the research! However that also means that it's not actionable for me. Closet relies of the functionality that was introduced with Android 10. However I'll pin the issue for others to see.
