### ISSUE TITLE
Update closetjs on npm to 0.5.1

### ISSUE THREAD

**Issue by kleinerpirat** [hgiesel/closet#76]
I was very pleased to find your [Closet Node package](https://www.npmjs.com/package/closetjs), but sadly it's only v0.4.8-1.
Do you intend to keep Closet updated on npm? I see a lot of potential there.

**Comment by hgiesel** [comment]
Sure! I think my main motivation was to just the experience of publishing a package to NPM. May I ask what parts of Closet you're interested in using as a lib?

**Comment by hgiesel** [comment]
I've bumped NPM to 0.5.4, which also includes a few additional bugfixes

**Comment by kleinerpirat** [comment]
Thanks a lot!

As I have externalized my complete note type to a Svelte app, making my [pre-template](https://github.com/hgiesel/closet/issues/56#issuecomment-849914864) translation asynchronous, I needed to postpone Closet's execution a bit.

At first, I just hacked my way through it and removed the Closet setup script from the DOM and reinserted it when the pre-template steps where finished. But with your NPM package, I can just `import { closet } from "closetjs"` and use an async function to init Closet myself:
```
export async function initCloset(args) {
    let [back, idx, tags] = args
    let cardidx = `Card ${idx}`
    closet.template.anki.initialize(
      closet,
      closetUserLogic,
      cardidx,
      tags,
      back ? "back" : "front",
    )
}
```
I got that to work with 0.4.8-1 already, but staying up-to-date via NPM would be great!

---
One feature I'd really enjoy would be to be able to **define a target node** for Closet, like MathJax allows you to do: `MathJax.typesetPromise([el])`. Currently, my Svelte app is inserted outside of `#qa` on Anki Desktop, AnkiWeb and AnkiMobile, so I don't have to reinstantiate the whole thing on each card.

If I could tell Closet to execute on the app's `main` node (instead of some hidden dummy divs), that would save a lot of passing around arguments and save some memory. One could create arbitrarily big notes and execute Closet only on the parts needed for that card, and re-execute it when needed. Closet is already super fast, but it still feels wrong executing it on hidden parts.

**Comment by hgiesel** [comment]
> One feature I'd really enjoy would be to be able to define a target node for Closet, like MathJax allows you to do.

This should already be possible. This type of `closetUserLogic` is `UserLogic`, which is defined like this:

```
type SetupOutput = [Element[], MemoryMap, TagRenderer, SetupOptions?];

type UserLogic<T extends Record<string, unknown>> = (
    closet: Record<string, unknown>,
    preset: T,
    chooseMemory: (memoryKey: string) => MemoryMap,
) => SetupOutput[];
```

So if the return value of the function is `[[el], memoryMap, filterManager]`, Closet should parse `el` instead. Of course you can also pass in multiple elements, and it should work fine. In fact in my personal, that's what I do. I just default to `#qa`, because it's a good default without making any assumptions about the template.

**Comment by kleinerpirat** [comment]
Awesome, thanks!
