### ISSUE TITLE
color change of image occlusion boxes?

### ISSUE THREAD

**Issue by ankidoc** [hgiesel/closet#82]
Tried to change the color from the yellow to different colors, but that didn't work because I didn't really find it in the code. How can I do that?

Greetings

**Comment by swkidd** [comment]
You can use CSS selectors for this. There may be a better way, but this seems to work.

.is-front:not(.is-active) rect {
  fill: some-color !important;
  stroke: some-other-color !important;
}

to change the color of all non active rectangles.

Or use .is-active as the selector for actice rectangles.

**Comment by ankidoc** [comment]
thanks that worked!
