### ISSUE TITLE
GUI files are compiled for Qt6 only

### ISSUE THREAD

**Issue by dollajas** [hgiesel/closet#97]
Update rolled out yesterday - now getting this error on start up: https://imgur.com/MDUPhnZ

**Comment by hgiesel** [comment]
The issue is, that you're running the Qt5 version, whereas we compile the GUI files for Qt6 now.

**Comment by kleinerpirat** [comment]
Working on it, along with fixes for #96.

**Comment by AnKingMed** [comment]
@kleinerpirat what's the status on Qt5 updates?  Also, I've had multiple people message me saying that their IO-one by one note types aren't working anymore.  I can't get them to work on 2.1.49 or 2.1.54 qt5 or qt6. Is that related to what's going on with these changes? 

see https://github.com/AnKingMed/AnKing-Note-Types

**Comment by AnKingMed** [comment]
I think we fixed the issue with the IO one by one note type (turned out to be the Edit Field During Review Cloze add-on), but still would be good to update for Qt5. @kleinerpirat any updated timeline on that?

**Comment by kleinerpirat** [comment]
It should be relatively easy to add Qt5 support, but that's not the main issue. There are some serious bugs that can cause unintentional content deletion/overrides of editor fields.

The add-on not working on Qt5 is actually a good safeguard :)

I've been working on a fix for the past few days and if everything goes well, I'll open a PR by Monday.

**Comment by AnKingMed** [comment]
Awesome. Good to hear I haven't been using it if that's the case :P    Once you do have it working, please get it working on Qt5 as I think most people will be using that at least for a bit.

**Comment by BEST8OY** [comment]
> I think we fixed the issue with the IO one by one note type (turned out to be the Edit Field During Review Cloze add-on), but still would be good to update for Qt5. @kleinerpirat any updated timeline on that?

Yeah
It happend in 2022-06-27 Update of Edit Field During Review Cloze add-on! I disabled it after update.
**It caused a problem with not showing occlusion boxes in answaring menu.**
Today I updated your addon and re-enabled said add-on and the problem is solved.

**Comment by dollajas** [comment]
Will closet be compatible with Qt5? Thanks for your support
